function Q_nd = Q_don_nd_9dof_10ab11_1000h1_R11(in1,in2,tau)
%Q_DON_ND_9DOF_10AB11_1000H1_R11
%    Q_ND = Q_DON_ND_9DOF_10AB11_1000H1_R11(IN1,IN2,TAU)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    08-Nov-2018 10:55:47

dxi1 = in1(10,:);
dxi2 = in1(11,:);
dxi3 = in1(12,:);
dxi4 = in1(13,:);
dxi5 = in1(14,:);
dxi6 = in1(15,:);
dxi7 = in1(16,:);
dxi8 = in1(17,:);
dxi9 = in1(18,:);
f_N = in2(:,1);
ome_f = in2(:,2);
Q_nd = [dxi1.*(-2.0e-5);dxi2.*(-2.0e-5);dxi3.*(-5.410077079789133e-5);dxi4.*(-5.410077079789133e-5);dxi5.*(-5.410077079789133e-5);dxi6.*(-5.410077079789133e-5);dxi7.*(-9.393022913910067e-5);dxi8.*(-9.393022913910067e-5);dxi9.*(-2.0e-5)+f_N.*cos(ome_f.*tau.*1.050133366937601e-3).*5.655282504388217e-2];
