function Q = Q_don_9dof_10ab11_1000h1_R11_1000z114(in1,in2,t)
%Q_DON_9DOF_10AB11_1000H1_R11_1000Z114
%    Q = Q_DON_9DOF_10AB11_1000H1_R11_1000Z114(IN1,IN2,T)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    06-Nov-2018 08:21:48

du11 = in1(10,:);
du13 = in1(12,:);
du31 = in1(14,:);
du33 = in1(16,:);
dv11 = in1(11,:);
dv13 = in1(13,:);
dv31 = in1(15,:);
dv33 = in1(17,:);
dw11 = in1(18,:);
f_N = in2(:,1);
ome_f = in2(:,2);
Q = [du11.*(-1.90452e-2);dv11.*(-1.90452e-2);du13.*(-5.1518e-2);dv13.*(-5.1518e-2);du31.*(-5.1518e-2);dv31.*(-5.1518e-2);du33.*(-8.944600000000001e-2);dv33.*(-8.944600000000001e-2);dw11.*(-1.90452e-2)+f_N.*cos(ome_f.*t).*5.128205128205128e1];
