function Q = Q_don_9dof_10ab11_1000h1_R11_1000z114_full(in1,f_N,ome_f,t)
%Q_DON_9DOF_10AB11_1000H1_R11_1000Z114_FULL
%    Q = Q_DON_9DOF_10AB11_1000H1_R11_1000Z114_FULL(IN1,F_N,OME_F,T)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    01-Sep-2018 08:27:47

du11 = in1(1,:);
du13 = in1(3,:);
du31 = in1(5,:);
du33 = in1(7,:);
dv11 = in1(2,:);
dv13 = in1(4,:);
dv31 = in1(6,:);
dv33 = in1(8,:);
dw11 = in1(9,:);
Q = [du11.*(-1.90452e-2);dv11.*(-1.90452e-2);du13.*(-5.1518e-2);dv13.*(-5.1518e-2);du31.*(-5.1518e-2);dv31.*(-5.1518e-2);du33.*(-8.944600000000001e-2);dv33.*(-8.944600000000001e-2);dw11.*(-1.90452e-2)+f_N.*cos(ome_f.*t).*5.128205128205128e1];
