function Q_nd = Q_don_nd_9dof_10ab11_1000h1_R11_1000z114_full_cou_no(in1,f_N,ome_f,tau)
%Q_DON_ND_9DOF_10AB11_1000H1_R11_1000Z114_FULL_COU_NO
%    Q_ND = Q_DON_ND_9DOF_10AB11_1000H1_R11_1000Z114_FULL_COU_NO(IN1,F_N,OME_F,TAU)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    01-Sep-2018 08:27:48

dxi1 = in1(1,:);
dxi2 = in1(2,:);
dxi3 = in1(3,:);
dxi4 = in1(4,:);
dxi5 = in1(5,:);
dxi6 = in1(6,:);
dxi7 = in1(7,:);
dxi8 = in1(8,:);
dxi9 = in1(9,:);
Q_nd = [dxi1.*(-2.0e-5);dxi2.*(-2.0e-5);dxi3.*(-5.410077079789133e-5);dxi4.*(-5.410077079789133e-5);dxi5.*(-5.410077079789133e-5);dxi6.*(-5.410077079789133e-5);dxi7.*(-9.393022913910067e-5);dxi8.*(-9.393022913910067e-5);dxi9.*(-2.0e-5)+f_N.*cos(ome_f.*tau.*1.050133366937601e-3).*5.655282504388217e-2];
