function Q_nd = Q_don_nd_9dof_10ab11_1000h1_R11_1000z110_full_cou_no(in1,f_N,ome_f,tau)
%Q_DON_ND_9DOF_10AB11_1000H1_R11_1000Z110_FULL_COU_NO
%    Q_ND = Q_DON_ND_9DOF_10AB11_1000H1_R11_1000Z110_FULL_COU_NO(IN1,F_N,OME_F,TAU)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    30-Aug-2018 08:10:32

Q_nd = [0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;f_N.*cos(ome_f.*tau.*1.050133366937601e-3).*5.655282504388217e-2];
