function Q = Q_don_9dof_10ab11_1000h1_R11_1000z1150_full(in1,f_N,ome_f,t)
%Q_DON_9DOF_10AB11_1000H1_R11_1000Z1150_FULL
%    Q = Q_DON_9DOF_10AB11_1000H1_R11_1000Z1150_FULL(IN1,F_N,OME_F,T)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    29-Aug-2018 09:46:01

du11 = in1(1,:);
du13 = in1(3,:);
du31 = in1(5,:);
du33 = in1(7,:);
dv11 = in1(2,:);
dv13 = in1(4,:);
dv31 = in1(6,:);
dv33 = in1(8,:);
dw11 = in1(9,:);
Q = [du11.*(-2.38065e-1);dv11.*(-2.38065e-1);du13.*(-6.439750000000002e-1);dv13.*(-6.439750000000002e-1);du31.*(-6.439750000000002e-1);dv31.*(-6.439750000000002e-1);du33.*(-1.118075);dv33.*(-1.118075);dw11.*(-2.38065e-1)+f_N.*cos(ome_f.*t).*5.128205128205128e1];
