function Q = Q_don_9dof_10ab11_1000h1_R11_1000z110_full(in1,f_N,ome_f,t)
%Q_DON_9DOF_10AB11_1000H1_R11_1000Z110_FULL
%    Q = Q_DON_9DOF_10AB11_1000H1_R11_1000Z110_FULL(IN1,F_N,OME_F,T)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    30-Aug-2018 08:10:32

Q = [0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;f_N.*cos(ome_f.*t).*5.128205128205128e1];
