function Q_nd = Q_don_nd_9dof_10ab11_1000h1_R11_1000z1150_full_cou_no(in1,f_N,ome_f,tau)
%Q_DON_ND_9DOF_10AB11_1000H1_R11_1000Z1150_FULL_COU_NO
%    Q_ND = Q_DON_ND_9DOF_10AB11_1000H1_R11_1000Z1150_FULL_COU_NO(IN1,F_N,OME_F,TAU)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    29-Aug-2018 09:46:02

dxi1 = in1(1,:);
dxi2 = in1(2,:);
dxi3 = in1(3,:);
dxi4 = in1(4,:);
dxi5 = in1(5,:);
dxi6 = in1(6,:);
dxi7 = in1(7,:);
dxi8 = in1(8,:);
dxi9 = in1(9,:);
Q_nd = [dxi1.*(-2.5e-4);dxi2.*(-2.5e-4);dxi3.*(-6.762596349736418e-4);dxi4.*(-6.762596349736418e-4);dxi5.*(-6.762596349736418e-4);dxi6.*(-6.762596349736418e-4);dxi7.*(-1.174127864238759e-3);dxi8.*(-1.174127864238759e-3);dxi9.*(-2.5e-4)+f_N.*cos(ome_f.*tau.*1.050133366937601e-3).*5.655282504388217e-2];
